In [1]:
import numpy as np 
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [2]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [3]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [4]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[ 58  98  83 100  92  86]


In [5]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.21541896 0.92010527 0.47350858 0.45469888 0.74323158 0.84142532]


In [6]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.21541896 2.92010527 2.47350858 2.45469888 2.74323158 2.84142532]


In [7]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[174 294 249 300 276 258]


In [13]:
#Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
#Assign 15 values to a NumPy array named label such that:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [15]:
#Add Some Noise to the Dataset by adding a different random floating-point value between -2 and +2 to the label.
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[-1.92528267 -0.02116271  0.21581198  0.70087154 -0.98902769 -1.21063816
  0.31687507 -0.95874855  1.91411588  1.21570216 -0.9222234  -1.6424131
 -0.71493036 -1.21160028 -0.05088288]
[20.07471733 24.97883729 28.21581198 31.70087154 33.01097231 35.78936184
 40.31687507 42.04125145 47.91411588 50.21570216 51.0777766  53.3575869
 57.28506964 59.78839972 63.94911712]
